device: AXIS_F41
ip: 192.168.10.195
port: 554
channel:
  rgb: 2
  rgb2: 1
  thermal: 3

optical_resolution: [720, 1280]
thermical_resolution:  [680, 480]
product_webseite: https://www.axis.com/products/axis-f41-main-unit/support
