auto_charge_return: false
battery_threshold: 9
charge_detection_radius: 0.8
charge_point:
  latitude: 48.65470876874471
  longitude: 9.226265314527641
  yaw: -93.3009283485678
enable_obstacle_avoidance: false
home_point:
  latitude: 48.654726705242204
  longitude: 9.226266880544673
home_tolerance: 0.5
max_route_distance: 3.0
security_always_enable_event_types: []
security_email:
  enabled: false
  password: ''
  recipients: []
  sender: ''
  smtp_host: ''
  smtp_port: 587
  use_tls: true
  username: ''
security_email_notification_timeout_seconds: 60
security_event_defaults:
  post_event_seconds: 10.0
  pre_event_seconds: 10.0
security_notification_windows: []
security_video_capture_timeout_seconds: 60
speed_factor: 1.406
waypoint_tolerance: 0.5
