auto_charge_return: true
battery_threshold: 28
charge_detection_radius: 0.8
charge_point:
  latitude: 48.65457244445798
  longitude: 9.224030264874573
  yaw: 168.87882450191105
enable_obstacle_avoidance: false
home_point:
  latitude: 48.65456897903391
  longitude: 9.22405695122272
home_tolerance: 0.5
max_route_distance: 3.0
security_always_enable_event_types: []
security_email:
  enabled: false
  password: ''
  recipients: []
  sender: ''
  smtp_host: ''
  smtp_port: 587
  use_tls: true
  username: ''
security_email_notification_timeout_seconds: 60
security_event_defaults:
  post_event_seconds: 10.0
  pre_event_seconds: 10.0
security_notification_windows: []
security_video_capture_timeout_seconds: 60
speed_factor: 0.988
waypoint_tolerance: 0.5
