# Basis-Image: ROS 2 Jazzy (arm64)
FROM arm64v8/ros:jazzy-ros-base
# Umgebungsvariablen
ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=jazzy
# System-Updates und grundlegende Tools
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-colcon-common-extensions \
    python3-opencv \
    build-essential \
    git \
    libyaml-cpp-dev \
    libboost-all-dev \
    zlib1g-dev \
    libeigen3-dev \
    linux-libc-dev \
    nlohmann-json3-dev \
    ros-jazzy-joy \
    python3-serial \
    python3-pyproj\
    ros-jazzy-cv-bridge\
    ros-jazzy-geographic-msgs \
    nano \
    tree \
    screen \
    && rm -rf /var/lib/apt/lists/*
RUN ln -s /opt/ros/jazzy/lib/libfastcdr.so.2.2.7 /opt/ros/jazzy/lib/libfastcdr.so.2.2.5
# Workspace-Verzeichnis
WORKDIR /app/ros2_ws
# Copy requirements.txt and install Python dependencies
COPY requirements-ros2_jetson.txt /tmp/requirements.txt
RUN pip3 install --no-cache-dir --ignore-installed -r /tmp/requirements.txt --break-system-packages && \
    rm /tmp/requirements.txt
# ROS-Umgebung laden
SHELL ["/bin/bash", "-c"]
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> ~/.bashrc && \
    echo "[ -f /app/ros2_ws/install_ros2/setup.bash ] && source /app/ros2_ws/install_ros2/setup.bash" >> ~/.bashrc
# Default-CMD: Bash mit ROS geladen
CMD ["bash", "-c", "source /opt/ros/${ROS_DISTRO}/setup.bash && exec bash"]
